# Etapa de construcción
FROM oven/bun:latest AS build
WORKDIR /app
COPY . .
RUN bun install
RUN bun run build

# Etapa de producción (Nginx)
FROM nginx:alpine
# Copiamos los archivos generados por Vite (usualmente en la carpeta /dist)
COPY --from=build /app/dist /usr/share/nginx/html
# Copiamos la configuración personalizada de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
